# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0  # Use a versão mais recente
    hooks:
      - id: black
        language_version: python3  # Altere para a versão do Python que você usa

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0  # Use a versão mais recente
    hooks:
      - id: flake8
